export const memories = [
    { date: "2024-04-28", from: "Möller", message: "Ingen som dig" },
    { date: "2024-04-29", from: "Kevin McCullagh", message: "All you need is avicii <3" },
    { date: "2024-04-30", from: "William", message: "Tänker på dig brorsan❤️" },
    { date: "2024-05-01", from: "Rimu", message: "Simple in two words 'the legend'" },
    { date: "2024-05-02", from: "Adrien", message: "you will always remain my favorite dj, your music gives me the joy of living, thank you!" },
    { date: "2024-05-03", from: "T", message: "Du fick mig att börja med musik Tim, tack för all glädje du inbringat i mitt liv. Vila i frid" },
    { date: "2024-05-04", from: "WaterfallEDM", message: "The first time I heard your song was in 2015 Rly liked 'Waiting for love' and 'I'll be gone' A big pity that I didn't know more about you until 2022 What I'm going to do is to make more music and finish your dream AVICII FOREVER ◢ ◤" },
    { date: "2024-05-05", from: "Sandra", message: "Your story holds a special place in my heart. As for your music, it makes me feel alive." },
    { date: "2024-05-06", from: "Rizky Artonobudi", message: "It's 2024, I still love your music. Love you so much Tim x ❤️" },
    { date: "2024-05-07", from: "Nabil", message: "#Hey Brother, one of the saddest memorable #Stories that I can't forget was your death. You were always #True. Your presence had a huge impact on me on different #levels. You showed me that you were a #True Believer when it came to music. Ever since you left us, # The Days and # The nights were hard. As if we couldn't see #Citylights anymore. oh #Dear Boy im proud of the person I am because #YouMakeMe believe so. Dear #Tim, I #HoldTheline everyday and I hope that you #NeverLeaveMe." },
    { date: "2024-05-08", from: "Kelsea", message: "Jag kommer älska dig och du skulle aldrig dö." },
    { date: "2024-05-09", from: "Laura", message: "And those who were seen dancing were thought to be insane by those who could not hear the music Miss you" },
    { date: "2024-05-10", from: "Zane", message: "For Tim. I will do it for you, bro. I will live the life I want for you. And it all starts now. Not tomorrow. Not later. Now. I live now. ◢ ◤" },
    { date: "2024-05-11", from: "Hanna.T", message: "Du fattas hos oss Tim❤️ hoppas du har det bra där du befinner dig nu❤️❤️" },
    { date: "2024-05-12", from: "Nina◢ ◤", message: "I remember the first time I heard his music, I was 8. Me and my dad would play his music and that memory meant a lot to me, still does to this day. we all miss you Tim. Rest in peace and show those angels the big impact you left on so many people up there. ◢ ◤" },
    { date: "2024-05-13", from: "Olav", message: "I miss his personal and musical essence so much. It makes us see that we are all people and we have a limit and there is no time that I am not excited when listening to his music I still remember when I found out about his death he was 13 years old and honestly it shocked me a lot and I keep him alive in my thoughts." },
    { date: "2024-05-14", from: "Nina", message: "I remember the first time I heard his music, I was 8. Me and my dad would play his music and that memory meant a lot to me, still does to this day. we all miss you Tim. Rest in peace and show those angels the big impact you left on so many people up there." },
    { date: "2024-05-15", from: "Ilona", message: "Tim I miss you so much 🥰" },
    { date: "2024-05-16", from: "Nao 'NATHAN' West", message: "I miss you so much, TIM◢ ◤ So much…" },
    { date: "2024-05-17", from: "Natasha H.N.", message: "We miss you. I still listen to, dance to, and sing to your songs all the time. Needless to say, I'm still a fan. You were truly one in a million. Rest in peace — your songs will forever be in my heart." },
    { date: "2024-05-18", from: "Ibiza hang", message: "എന്റെ സ്വപ്നം മാത്രം ആയി നീ ഒന്നും അവശേഷിക്കുന്നില്ല 💛" },
    { date: "2024-05-19", from: "Bryan", message: "Siempre que me siento triste o deprimido escucho las canciones de Avicii, eso me ayuda a sentirme mejor y a olvidarme de los problemas, mis canciones favoritas de Avicii siempre fueron Wake Me Up, Waiting For Love, Hey Brother y Without You" },
    { date: "2024-05-20", from: "Jacky W.", message: "To this day, I still think of Avicii almost daily, ever since I first listened to 'Wake Me Up' in 2013." },
    { date: "2024-05-21", from: "Chengrui", message: "I have nothing but love. Avicii forever." },
    { date: "2024-05-22", from: "Antoine", message: "One day you'll leave" },
    { date: "2024-05-23", from: "Lisa", message: "Your music still inspires me every day. Rest in peace, Tim." },
    { date: "2024-05-24", from: "Jonas", message: "Avicii, your legacy lives on. We miss you!" },
    { date: "2024-05-25", from: "Emma", message: "Thank you for the music, Tim. You are missed dearly." },
    { date: "2024-05-26", from: "Carlos", message: "Tus canciones son inmortales. Gracias por todo, Avicii." },
    { date: "2024-05-27", from: "Mia", message: "Forever in our hearts, Avicii. Your music is timeless." },
    { date: "2024-05-28", from: "Raj", message: "You left us too soon, but your music will always be with us. RIP Avicii." },
    { date: "2024-05-29", from: "Sara", message: "Your music touched my soul. You are forever missed, Avicii." },
    { date: "2024-05-30", from: "Thomas", message: "Avicii, your music will always be a part of my life. Rest in peace." },
    { date: "2024-05-31", from: "Isabella", message: "Thank you for the memories and the music, Avicii. You are forever in our hearts." },
    { date: "2024-04-28", from: "Möller", message: "Ingen som dig" },
    { date: "2024-04-29", from: "Kevin McCullagh", message: "All you need is avicii <3" },
    { date: "2024-04-30", from: "William", message: "Tänker på dig brorsan❤️" },
    { date: "2024-05-01", from: "Rimu", message: "Simple in two words 'the legend'" },
    { date: "2024-05-02", from: "Adrien", message: "you will always remain my favorite dj, your music gives me the joy of living, thank you!" },
    { date: "2024-05-03", from: "T", message: "Du fick mig att börja med musik Tim, tack för all glädje du inbringat i mitt liv. Vila i frid" },
    { date: "2024-05-04", from: "WaterfallEDM", message: "The first time I heard your song was in 2015 Rly liked 'Waiting for love' and 'I'll be gone' A big pity that I didn't know more about you until 2022 What I'm going to do is to make more music and finish your dream AVICII FOREVER ◢ ◤" },
    { date: "2024-05-05", from: "Sandra", message: "Your story holds a special place in my heart. As for your music, it makes me feel alive." },
    { date: "2024-05-06", from: "Rizky Artonobudi", message: "It's 2024, I still love your music. Love you so much Tim x ❤️" },
    { date: "2024-05-07", from: "Nabil", message: "#Hey Brother, one of the saddest memorable #Stories that I can't forget was your death. You were always #True. Your presence had a huge impact on me on different #levels. You showed me that you were a #True Believer when it came to music. Ever since you left us, # The Days and # The nights were hard. As if we couldn't see #Citylights anymore. oh #Dear Boy im proud of the person I am because #YouMakeMe believe so. Dear #Tim, I #HoldTheline everyday and I hope that you #NeverLeaveMe." },
    { date: "2024-05-08", from: "Kelsea", message: "Jag kommer älska dig och du skulle aldrig dö." },
    { date: "2024-05-09", from: "Laura", message: "And those who were seen dancing were thought to be insane by those who could not hear the music Miss you" },
    { date: "2024-05-10", from: "Zane", message: "For Tim. I will do it for you, bro. I will live the life I want for you. And it all starts now. Not tomorrow. Not later. Now. I live now. ◢ ◤" },
    { date: "2024-05-11", from: "Hanna.T", message: "Du fattas hos oss Tim❤️ hoppas du har det bra där du befinner dig nu❤️❤️" },
    { date: "2024-05-12", from: "Nina◢ ◤", message: "I remember the first time I heard his music, I was 8. Me and my dad would play his music and that memory meant a lot to me, still does to this day. we all miss you Tim. Rest in peace and show those angels the big impact you left on so many people up there. ◢ ◤" },
    { date: "2024-05-13", from: "Olav", message: "I miss his personal and musical essence so much. It makes us see that we are all people and we have a limit and there is no time that I am not excited when listening to his music I still remember when I found out about his death he was 13 years old and honestly it shocked me a lot and I keep him alive in my thoughts." },
    { date: "2024-05-14", from: "Nina", message: "I remember the first time I heard his music, I was 8. Me and my dad would play his music and that memory meant a lot to me, still does to this day. we all miss you Tim. Rest in peace and show those angels the big impact you left on so many people up there." },
    { date: "2024-05-15", from: "Ilona", message: "Tim I miss you so much 🥰" },
    { date: "2024-05-16", from: "Nao 'NATHAN' West", message: "I miss you so much, TIM◢ ◤ So much…" },
    { date: "2024-05-17", from: "Natasha H.N.", message: "We miss you. I still listen to, dance to, and sing to your songs all the time. Needless to say, I'm still a fan. You were truly one in a million. Rest in peace — your songs will forever be in my heart." },
    { date: "2024-05-18", from: "Ibiza hang", message: "എന്റെ സ്വപ്നം മാത്രം ആയി നീ ഒന്നും അവശേഷിക്കുന്നില്ല 💛" },
    { date: "2024-05-19", from: "Bryan", message: "Siempre que me siento triste o deprimido escucho las canciones de Avicii, eso me ayuda a sentirme mejor y a olvidarme de los problemas, mis canciones favoritas de Avicii siempre fueron Wake Me Up, Waiting For Love, Hey Brother y Without You" },
    { date: "2024-05-20", from: "Jacky W.", message: "To this day, I still think of Avicii almost daily, ever since I first listened to 'Wake Me Up' in 2013." },
    { date: "2024-05-21", from: "Chengrui", message: "I have nothing but love. Avicii forever." },
    { date: "2024-05-22", from: "Antoine", message: "One day you'll leave" },
    { date: "2024-05-23", from: "Lisa", message: "Your music still inspires me every day. Rest in peace, Tim." },
    { date: "2024-05-24", from: "Jonas", message: "Avicii, your legacy lives on. We miss you!" },
    { date: "2024-05-25", from: "Emma", message: "Thank you for the music, Tim. You are missed dearly." },
    { date: "2024-05-26", from: "Carlos", message: "Tus canciones son inmortales. Gracias por todo, Avicii." },
    { date: "2024-05-27", from: "Mia", message: "Forever in our hearts, Avicii. Your music is timeless." },
    { date: "2024-05-28", from: "Raj", message: "You left us too soon, but your music will always be with us. RIP Avicii." },
    { date: "2024-05-29", from: "Sara", message: "Your music touched my soul. You are forever missed, Avicii." },
  ];
  